# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: uname -a
  displayName: 'uname'

- script: |
    lshw -short
    head -n 1 /proc/meminfo
  displayName: 'lshw'
