apiVersion: apps/v1
kind: Deployment
metadata:
  name: azpagent-deployment
  labels:
    app: azpagent
spec:
  replicas: 4
  selector:
    matchLabels:
      app: azpagent
  template:
    metadata:
      labels:
        app: azpagent
    spec:
      containers:
      - name: azpagent
        image: localhost:32000/azpagent:registry
        env:
          - name: AZP_URL
            valueFrom:
              secretKeyRef:
                name: azure-microk8s-secret
                key: AZP_URL
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azure-microk8s-secret
                key: AZP_TOKEN

